tests(*) 03-cis-sec.test.sh
Kong/docker-kong pull request #459
Opened 2021-04-26 15:51 UTC by kikito

2021-04-27 06:38 UTC, Tieske requested changes

2021-04-27 06:38 UTC, Tieske commented on tests/03-cis-sec.test.sh
> +  ttest "CIS-Sec for docker-compose"
```suggestion
  tinitialize "Docker-Kong test suite" "${BASH_SOURCE[0]}"

  tchapter "CIS-Sec tests $KONG_DOCKER_TAG"
  ttest "CIS-Sec for docker-compose"
```

2021-04-27 06:38 UTC, Tieske commented on tests/03-cis-sec.test.sh
> +      tfailure
```suggestion
      tmessage "Could not clone docker-bench-security"
      tfailure
```

2021-04-27 06:38 UTC, Tieske commented on tests/03-cis-sec.test.sh
> +        tfailure
```suggestion
        tmessage "Could not execute docker-bench-security"
        tfailure
```

2021-04-27 06:38 UTC, Tieske commented on tests/03-cis-sec.test.sh
> +    tfailure
```suggestion
    tmessage "Found warnings in docker-bench-security report"
    tfailure
```

2021-04-30 15:50 UTC, dndx approved these changes

2021-04-30 16:13 UTC, Tieske approved these changes
lgtm

2021-04-30 16:14 UTC, murillopaula commented
sorry haven't had bandwidth to review this one... can you take a look at the failing tests? also there are some pending FIXME comments, should we merge with those?

2021-05-01 06:44 UTC, Tieske commented
hmmm I assumed it to be the docker rate limit kicking in, but it seems all jobs fail on the same test. So yes, we need the tests fixed. Thx @murillopaula

2021-05-05 20:08 UTC, hutchic commented on compose/docker-compose.yml
> +    cpu_shares: 1024
```suggestion
```

This is applicable to docker-compose version 2 only and is the current build failure

```
Server: openresty

Compose file contains unsupported options:

cpu_shares: Set resource limits using deploy.resources
```

2021-05-05 20:22 UTC, hutchic commented on compose/docker-compose.yml
> +    pids_limit: 100
```suggestion
```

docker-compose version three docs say "this hasn't been introduced"

> pids_limit: This option has not been introduced in version: "3.x" Compose files.

2021-05-05 20:24 UTC, hutchic commented
after the two docker-compose version three compatibility fixes I'm hitting the following locally
```
kong_kong.1.9v8lhvns3xsp@ip-172-31-30-251    | stack traceback:
kong_kong.1.9v8lhvns3xsp@ip-172-31-30-251    |  [C]: in function 'assert'
kong_kong.1.9v8lhvns3xsp@ip-172-31-30-251    |  /usr/local/share/lua/5.1/kong/init.lua:448: in function 'init'
kong_kong.1.9v8lhvns3xsp@ip-172-31-30-251    |  init_by_lua:3: in main chunk
kong_kong.1.pkwhtdjok3c4@ip-172-31-30-251    | nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/kong/nginx.conf:6
kong_kong.1.pkwhtdjok3c4@ip-172-31-30-251    | 2021/05/05 20:20:46 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:448: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: host or service not provided, or not known
```

2021-06-02 16:42 UTC, gszr approved these changes

2021-06-02 17:31 UTC, merged